# Generated by Django 5.2 on 2025-05-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_roadmap_delete_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='domain_test_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='domain_test_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interest_test_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roadmap_visited',
            field=models.BooleanField(default=False),
        ),
    ]
