# Generated by Django 5.2 on 2025-05-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_userprofile_domain_test_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='domain_test_score',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='domain_test_taken',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='interest_test_taken',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='roadmap_visited',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
