# Generated by Django 5.2 on 2025-05-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_remove_userprofile_domain_test_score_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
