# Generated by Django 5.2 on 2025-05-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0006_delete_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
