# Generated by Django 5.2 on 2025-05-08 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0007_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interestresult',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='interestresult',
            name='test_score',
        ),
        migrations.RemoveField(
            model_name='interestresult',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='completed_courses',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='progress_percentage',
        ),
        migrations.AddField(
            model_name='interestresult',
            name='recommended_domains',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='courses_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='domain_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='roadmap_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='test_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='progress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
