# Generated by Django 5.2 on 2025-05-08 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0009_remove_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
