# Generated by Django 5.2 on 2025-05-09 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0010_alter_roadmap_generated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestoption',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='career.domain'),
        ),
    ]
